### ISSUE TITLE
Component wont work in hass 0.92.0

### ISSUE THREAD

**Issue by RPaulsson** [custom-components/feedparser#12]
Hello, 

I get this errer for the component.

"Integration feedparser not found when trying to verify its sensor platform."

//Rickard

**Comment by jimz011** [comment]
I can't get it to work either (though I haven't tested it on older versions as I have just installed this for the first time)
I get the following error:
`
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 46, in setup_platform
    add_devices([FeedParserSensor(hass, config)])
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 58, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/feedparser/sensor.py", line 61, in update
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
`

**Comment by iantrich** [comment]
Is this still an issue now that manifest.json is available? Thanks.

**Comment by ikifar2012** [comment]
This issue should be fixed with this PR to Home Assistant:
https://github.com/home-assistant/home-assistant/pull/25005
